language: erlang

otp_release:
  - 21.0
  - 21.3
  - 22.0
  - 24.0

before_install:
  - >
    case $TRAVIS_OTP_RELEASE in
    21.*) REBAR_URL=https://github.com/erlang/rebar3/releases/download/3.15.2/rebar3;;
       *) REBAR_URL=https://s3.amazonaws.com/rebar3/rebar3;;
    esac
  - mkdir $PWD/bin
  - curl -Lo $PWD/bin/rebar3 $REBAR_URL
  - chmod +x $PWD/bin/rebar3
  - export PATH=$PWD/bin:$PATH

install:
  - rebar3 get-deps

script:
  - rebar3 compile
  - rebar3 xref
  - rebar3 dialyzer
  - rebar3 ct
